apiVersion: apps/v1
kind: Deployment
metadata:
  name: e1streamv2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e1streamv2
    spec:
      containers:
      - name: e1streamv2
        image: localhost:32000/monitoringdatadataloggingservice:e1streamv2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: e1streamv2
---
apiVersion: v1
kind: Service
metadata:
  name: e1streamv2
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: e1streamv2