apiVersion: apps/v1
kind: Deployment
metadata:
  name: e1streamdev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e1streamdev
    spec:
      containers:
      - name: e1streamdev
        image: localhost:32000/monitoringdatadataloggingservice:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DEVICEID
          value: epi1
        - name: SERVICE_TYPE
          value: MonitorBox
  selector:
    matchLabels:
      app: e1streamdev
---
apiVersion: v1
kind: Service
metadata:
  name: e1streamdev
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: e1streamdev