apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2streamdev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e2streamdev
    spec:
      containers:
      - name: e2streamdev
        image: localhost:32000/monitoringdatadataloggingservice:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DEVICEID
          value: epi2
        - name: SERVICE_TYPE
          value: MonitorBox
      nodeSelector:
        nodes: node02
  selector:
    matchLabels:
      app: e2streamdev
---
apiVersion: v1
kind: Service
metadata:
  name: e2streamdev
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: e2streamdev