apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbstreamdev
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gbstreamdev
    spec:
      containers:
      - name: gbstreamdev
        image: localhost:32000/monitoringdatadataloggingservice:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DEVICEID
          value: gasbay
        - name: SERVICE_TYPE
          value: MonitorBox
      nodeSelector:
        nodes: node02
  selector:
    matchLabels:
      app: gbstreamdev
---
apiVersion: v1
kind: Service
metadata:
  name: gbstreamdev
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: gbstreamdev