apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbstream
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gbstream
    spec:
      containers:
      - name: gbstream
        image: localhost:32000/monitoringdatadataloggingservice:gbstream
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: gbstream
---
apiVersion: v1
kind: Service
metadata:
  name: gbstream
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: gbstream