apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhstreamdev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nhstreamdev
    spec:
      containers:
      - name: nhstreamdev
        image: localhost:32000/monitoringdatadataloggingservice:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DEVICEID
          value: nh3
        - name: SERVICE_TYPE
          value: GenericModbus
      nodeSelector:
        nodes: master
  selector:
    matchLabels:
      app: nhstreamdev
---
apiVersion: v1
kind: Service
metadata:
  name: nhstreamdev
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nhstreamdev