apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappv1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webappv1
    spec:
      containers:
      - name: webappv1
        image: localhost:32000/monitoringwebwebapp:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: webappv1
---
apiVersion: v1
kind: Service
metadata:
  name: webappv1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webappv1