apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webappdev
    spec:
      containers:
      - name: webappdev
        image: localhost:32000/monitoringwebwebapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: webappdev
---
apiVersion: v1
kind: Service
metadata:
  name: webappdev
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webappdev