apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2streamv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: e2streamv
    spec:
      containers:
      - name: e2streamv
        image: localhost:32000/monitoringdatadataloggingservice:e2streamv
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: e2streamv
---
apiVersion: v1
kind: Service
metadata:
  name: e2streamv
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: e2streamv