apiVersion: apps/v1
kind: Deployment
metadata:
  name: textwebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: textwebapp
    spec:
      containers:
      - name: textwebapp
        image: aelmendorf234/smswebapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: textwebapp
---
apiVersion: v1
kind: Service
metadata:
  name: textwebapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: textwebapp